-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDUzETNxhKnVHYgjl
EIRcTVTKLbnFRVFCupBGri2JHi6gCgYIKoZIzj0DAQehRANCAASn1c6sP5kqjT/s
VHnenSmoaOMuqeNm6zZ7XowyhsOzbbDcrc+Ede2NufteBP1argz1vzfrrXyiEhUz
wEav+Sos
-----END PRIVATE KEY-----